FROM python:3.7 as builder

COPY . /voluba
WORKDIR /voluba

RUN pip install mkdocs mkdocs-material
RUN mkdocs build

FROM httpd:2-alpine
COPY --from=builder /voluba/site/ /usr/local/apache2/htdocs/

ENTRYPOINT ["httpd-foreground"]