site_name: Voluba User Documentation

theme:
  name: 'readthedocs'

extra_css:
  - extra.css

docs_dir: user_docs

markdown_extensions:
  - admonition
  - codehilite
  - mdx_truly_sane_lists

nav:
  - Home: 'index.md'
  - 'acknowledgement.md'
  - 'requirements.md'
  - 'input.md'
  - 'alignment.md'
